<a href="https://colab.research.google.com/github/raamiiChu/NCCU_110-2_Group26_Applications-of-mathematics-softwares/blob/main/%E6%B8%AC%E8%A9%A6%E7%94%A8/%E6%B8%AC%E8%A9%A6%E8%AA%9E%E9%9F%B3%E8%BD%89%E6%95%B8%E5%AD%97_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://huggingface.co/TalTechNLP/voxlingua107-epaca-tdnn

In [ ]:
!pip install speechbrain

     |████████████████████████████████| 408 kB 5.2 MB/s 
     |████████████████████████████████| 1.2 MB 48.3 MB/s 
     |████████████████████████████████| 109 kB 54.0 MB/s 
     |████████████████████████████████| 546 kB 56.1 MB/s 
  Created wheel for hyperpyyaml: filename=HyperPyYAML-1.0.1-py3-none-any.whl size=15192 sha256=286e5245750fe4cebe0a19c16320ab0d370fb39377d28355d137f4ce7797a585
  Stored in directory: /root/.cache/pip/wheels/6c/87/65/266d722c3932f81f16332ce842e972be8421e3a9cd3771766b
Successfully built hyperpyyaml


In [ ]:
import torchaudio
from speechbrain.pretrained import EncoderClassifier
language_id = EncoderClassifier.from_hparams(source="TalTechNLP/voxlingua107-epaca-tdnn", savedir="tmp")

/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_deprecation.py:43: FutureWarning: Pass library_name=False as keyword args. From version 0.7 passing these as positional arguments will result in an error
  FutureWarning,


Downloading:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/84.5M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/110k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.22k [00:00<?, ?B/s]

In [ ]:
file_name = "/content/common_voice_zh-TW_17367893.mp3"
signal = language_id.load_audio(file_name)
prediction =  language_id.classify_batch(signal)

In [ ]:
# prediction[0]: cosine scores
# prediction[1]: 我不知道這代表甚麼
# prediction[2]: 語言代碼(0~106)
# prediction[3]: 代碼所對應的語言
prediction

(tensor([[0.2876, 0.2440, 0.2358, 0.2753, 0.2634, 0.2170, 0.1904, 0.2284, 0.2691,
          0.2804, 0.3129, 0.2952, 0.2125, 0.2437, 0.1508, 0.2490, 0.2731, 0.3815,
          0.2717, 0.2699, 0.3107, 0.1904, 0.2308, 0.2815, 0.2568, 0.2749, 0.2602,
          0.2797, 0.2410, 0.2257, 0.1210, 0.1604, 0.3247, 0.2500, 0.3143, 0.2527,
          0.2530, 0.2552, 0.2667, 0.2206, 0.1476, 0.2598, 0.2628, 0.1634, 0.2668,
          0.3694, 0.2777, 0.2628, 0.2876, 0.2638, 0.2692, 0.3405, 0.2939, 0.2563,
          0.2119, 0.2867, 0.2584, 0.2319, 0.2455, 0.2563, 0.2579, 0.2334, 0.2921,
          0.2478, 0.2776, 0.2652, 0.3712, 0.2278, 0.2961, 0.2772, 0.2576, 0.1459,
          0.2327, 0.2538, 0.2139, 0.2471, 0.2390, 0.2434, 0.2664, 0.2695, 0.2775,
          0.1932, 0.1872, 0.2576, 0.2323, 0.2708, 0.2370, 0.2540, 0.2931, 0.3098,
          0.1973, 0.2739, 0.2243, 0.2374, 0.3180, 0.2699, 0.2582, 0.2387, 0.2570,
          0.2244, 0.2610, 0.2574, 0.2984, 0.2400, 0.2092, 0.2500, 0.8569]]),
 tensor([0.8569]),
 t

In [ ]:
prediction[3]

['zh']

In [ ]:
# embedding
emb =  language_id.encode_batch(signal)
print(emb.shape)

torch.Size([1, 1, 256])


In [ ]:
emb

tensor([[[ -7.1007,   6.4022,   9.1268,  12.3954,  -5.3381,   2.6122,   4.6086,
           -3.2300,   2.2921,  -5.8211,  -6.5002,  -7.8933, -19.1284,   7.2749,
           -7.5857,   7.1524,  -5.7338,   1.8097,   7.4984,  -5.7045,   1.9947,
           -8.8974,   5.6657,   5.2232,   0.7452,  -7.4245,   6.0741,   6.0146,
          -10.8843,   7.6757,   3.0419,  -3.9115,  -1.5899,  10.1074,   0.9812,
           -2.1977,  -5.6119,   4.6379,   3.0169,   1.2482,  -4.4992,   5.3520,
            8.6852,  -9.4338,  -3.3253,  -6.5059,   6.4605,  -2.5154,   2.5783,
           -1.9182,   3.3781,  -3.5325,   9.3333,  14.4473,  10.8765,  -4.9603,
            2.3393,   1.1554,  -4.7712,   0.0786,   3.0689,   5.2567,   1.1692,
           -7.6348,  -1.9989,  -2.4469,  -0.7346,   3.1948,   2.5533,   9.7620,
            7.3970,  -2.8534,  -4.7541,  -6.2562,  -5.1552,   9.1861,   4.6046,
           -0.8086,   7.8939,   1.7648,  -4.3937,   4.9229,  -4.9341,  -6.6814,
            8.1630,  -1.9222,   6.7645, 